sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
env:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary
    
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache
    
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary

before_install:
    # setting the path for phantom.js 2.0.0
    - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - sh -e /etc/init.d/xvfb start
    - cd digital-signage-app-v2
    - "npm config set spin false"
    - "npm install -g npm@latest"
     - bower --version
    - npm install phantomjs-prebuilt
    - node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
    - npm install -g bower
    - npm install
    - bower install

script:
  - ember test --server
