---
sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
env:
  matrix:
    - TEST_DIR=digital-signage-app-v2
    - TEST_DIR=model-editor
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary
matrix:
  fast_finish: true
  allow_failures: 
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary
    
cache:
  directories:
    - node_modules
    - bower_components

# before_install:
#   - cd digital-signage-app-v2
#   - npm config set spin false
#   - npm install -g bower
#   - bower --version

# install:
#   - npm install
#   - bower install

script:
  - cd $TEST_DIR && npm instal -g bower && npm install && bower install && ember try:one $EMBER_VERSION --skip-cleanup=true --- ember test --reporter dot
    
