---
sudo: true
dist: trusty

language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  
env:
  - TEST_DIR=digital-signage-app-v2
  matrix:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary
  - TEST_DIR=model-editor
  matrix:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary

allowed_failures:
  - env: EMBER_VERSION=beta
  - env: EMBER_VERSION=canary

script: cd $TEST_DIR && npm install -g bower phantomjs-prebuilt && npm install && bower install && npm test
    
