---
sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
env:
  matrix:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary
    - TEST_DIR=digital-signage-app-v2
    - TEST_DIR=model-editor
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary
    
cache:
  directories:
    - node_modules
    - bower_components

script:
  - cd $TEST_DIR && npm install && bower install && ember try:one $EMBER_VERSION --skip-cleanup=true --- ember test --reporter dot
    
