---
sudo: true
dist: trusty

language: node_js
node_js:
  - "6"
  
env:
  - TEST_DIR=digital-signage-app-v2
  - TEST_DIR=model-editor

script: cd $TEST_DIR && npm install -g bower && npm install && bower install && npm test
    
